### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by damodaran** [azure-contrib/node-azure-search#21]
Getting TypeError: cb is not a function when azure uploadDocuments fails 

```
node_modules/azure-search/index.js:350
        if (err) return cb(err, null, data)
                        ^

TypeError: cb is not a function
    at ...../node_modules/azure-search/index.js:350:25
    at ClientRequest.<anonymous> (....../node_modules/azure-search/index.js:107:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1271:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

Azure error for uploadDocuments as follows

```
PUT /azureadmin/indexes - - ms - -
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1012:11)
    at TLSWrap.onread (net.js:563:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```

**Comment by richorama** [comment]
Hi @amodaran from your stack trace it looks like you were calling `updateIndex`. Are you supplying a callback as a third argument to the function?

Are you able to create a small reproduction of the error?
